
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from '../../components/Header/Header'
import i18nConfig from "@/i18nConfig";
import {dir} from 'i18next';
import Footer from "@/components/Footer/Footer";
const poppins = Poppins({ subsets: ["latin"],weight:['400','500','600','700','800','900'] });



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}


export default function RootLayout({
  children,
  params: {locale}
}: Readonly<{
  children: React.ReactNode;
  params: any;
}>) {
  return (
    <html lang={locale} dir={dir(locale)} >
      <body className={poppins.className}>
      <Header locale={locale}/>
          {children}
        <Footer locale={locale}/>
      </body>
    </html>
  );
}
